apiVersion: apps/v1
kind: Deployment
metadata:
  name: downstream
  namespace: tracing-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: downstream
  template:
    metadata:
      labels:
        app: downstream
      annotations:
        sidecar.istio.io/rewriteAppHTTPProbers: "false"
    spec:
      containers:
        - name: downstream
          image: prashanthsriram145/downstream:latest
          env:
            - name: OTEL_METRICS_EXPORTER
              value: "none"
          ports:
            - containerPort: 8080
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            periodSeconds: 5
            failureThreshold: 30
---
apiVersion: v1
kind: Service
metadata:
  name: downstream
  namespace: tracing-demo
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: downstream
